"""Command-line interface for datamultiplier."""

import click
from pathlib import Path

from .db.connection import DatabaseConnection
from .inspector import SchemaInspector
from .generator import DataGenerator
from .dumper import DataDumper
from .config import GenerationConfig


@click.group()
def main() -> None:
    """PostgreSQL test data generator for large-scale relational datasets.

    Quick Start:
        1. Inspect your database schema:
            datamultiplier inspect --db-url postgresql://user:pass@localhost/db \\
                --schema my_schema

        2. Edit schema.yaml to customize row counts and data generation rules

        3. Generate test data:
            datamultiplier generate --db-url postgresql://user:pass@localhost/db \\
                --schema my_schema --config schema.yaml --rows 1000000

        4. Export data:
            datamultiplier dump-all --db-url postgresql://user:pass@localhost/db \\
                --schema my_schema --output-dir ./backups

    Schema: By default, uses the user's search_path. Use --schema to override.

    Use --help with any command for more details:
        datamultiplier inspect --help
        datamultiplier generate --help
        datamultiplier dump --help
    """
    pass


@main.command()
@click.option(
    "--db-url",
    required=True,
    envvar="DATABASE_URL",
    help="PostgreSQL connection URL (e.g., postgresql://user:pass@localhost/db)",
)
@click.option(
    "--schema",
    default=None,
    help="Database schema name (default: user's search_path)",
)
@click.option(
    "--output",
    type=click.Path(),
    default="schema.yaml",
    help="Output YAML file path",
)
def inspect(db_url: str, schema: str, output: str) -> None:
    """Inspect database schema and generate YAML configuration.

    This command connects to a PostgreSQL database, reads all tables and their
    relationships, and generates a YAML configuration file that can be customized
    before data generation.
    """
    click.echo(f"Connecting to database...")
    click.echo(f"  Schema: {schema}")
    click.echo(f"  Output: {output}")

    db = DatabaseConnection(db_url, schema=schema)
    db.connect()
    click.echo(f"✓ Connected")

    try:
        click.echo(f"\nInspecting schema '{schema}'...")
        inspector = SchemaInspector(db)
        config = inspector.inspect_all_tables()

        click.echo(f"✓ Found {len(config.tables)} tables")
        for table in config.tables:
            click.echo(f"  - {table.name}: {len(table.columns)} columns")

        click.echo(f"\nGenerating configuration...")
        config.to_yaml(output)
        click.echo(f"✓ Configuration saved to '{output}'")

        click.echo(f"\nNext: Edit '{output}' to customize row counts and data rules, then run:")
        click.echo(f"  datamultiplier generate --db-url {db_url} --schema {schema} --config {output}")

    finally:
        db.disconnect()


@main.command()
@click.option(
    "--db-url",
    required=True,
    envvar="DATABASE_URL",
    help="PostgreSQL connection URL",
)
@click.option(
    "--schema",
    default=None,
    help="Database schema name (default: user's search_path)",
)
@click.option(
    "--config",
    type=click.Path(exists=True),
    required=True,
    help="YAML configuration file",
)
@click.option(
    "--rows",
    type=int,
    help="Override row count for all tables (optional)",
)
@click.option(
    "--seed",
    type=int,
    default=42,
    help="Random seed for reproducible data generation",
)
def generate(db_url: str, schema: str, config: str, rows: int, seed: int) -> None:
    """Generate test data based on YAML configuration.

    This command reads a YAML configuration file (typically generated by the
    'inspect' command) and generates large-scale test data respecting foreign
    key relationships and data generation rules.

    Example:
        datamultiplier generate --db-url postgresql://user:pass@localhost/mydb \\
            --config schema.yaml --rows 1000000 --seed 42
    """
    click.echo(f"Loading configuration from '{config}'...")

    config_obj = GenerationConfig.from_yaml(config)
    config_obj.seed = seed

    # Override row counts if specified
    if rows:
        for table in config_obj.tables:
            table.row_count = rows

    click.echo(f"\nGeneration settings:")
    click.echo(f"  Schema: {schema}")
    click.echo(f"  Seed: {config_obj.seed}")
    click.echo(f"\nTables to generate:")
    total_rows = 0
    for table in config_obj.tables:
        click.echo(f"  - {table.name}: {table.row_count:,} rows")
        total_rows += table.row_count
    click.echo(f"\nTotal: {total_rows:,} rows")

    if not click.confirm("Proceed with data generation?"):
        click.echo("Cancelled.")
        return

    click.echo(f"\nConnecting to database schema '{schema}'...")
    db = DatabaseConnection(db_url, schema=schema)
    db.connect()
    click.echo(f"✓ Connected")

    try:
        generator = DataGenerator(db, config_obj)
        generator.generate_all()

        click.echo(f"\n✓ Data generation complete!")
        click.echo(f"Generated {total_rows:,} rows across {len(config_obj.tables)} tables")

    finally:
        db.disconnect()


@main.command()
@click.option(
    "--db-url",
    required=True,
    envvar="DATABASE_URL",
    help="PostgreSQL connection URL",
)
@click.option(
    "--schema",
    default=None,
    help="Database schema name (default: user's search_path)",
)
@click.option(
    "--table",
    required=True,
    help="Table name to export",
)
@click.option(
    "--output",
    type=click.Path(),
    required=True,
    help="Output file path",
)
@click.option(
    "--format",
    type=click.Choice(["csv", "sql"]),
    default="csv",
    help="Export format",
)
@click.option(
    "--where",
    help="Optional WHERE clause to filter rows",
)
def dump(db_url: str, schema: str, table: str, output: str, format: str, where: str) -> None:
    """Export table data to CSV or SQL.

    Examples:
        # Export entire table to CSV
        datamultiplier dump --db-url postgresql://user:pass@localhost/mydb \\
            --table users --output users.csv

        # Export filtered data to SQL
        datamultiplier dump --db-url postgresql://user:pass@localhost/mydb \\
            --table orders --output recent_orders.sql --format sql \\
            --where "created_at > '2024-01-01'"
    """
    click.echo(f"Exporting table '{schema}.{table}' to {format.upper()}...")
    click.echo(f"  Output: {output}")

    db = DatabaseConnection(db_url, schema=schema)
    db.connect()
    click.echo(f"✓ Connected")

    try:
        dumper = DataDumper(db)

        if format == "csv":
            dumper.dump_table_to_csv(table, output, where_clause=where)
        elif format == "sql":
            dumper.dump_table_to_sql(table, output, where_clause=where)

        click.echo(f"✓ Export complete: {output}")

    finally:
        db.disconnect()


@main.command()
@click.option(
    "--db-url",
    required=True,
    envvar="DATABASE_URL",
    help="PostgreSQL connection URL",
)
@click.option(
    "--schema",
    default=None,
    help="Database schema name (default: user's search_path)",
)
@click.option(
    "--output-dir",
    type=click.Path(),
    default="./data_dump",
    help="Output directory for CSV files",
)
def dump_all(db_url: str, schema: str, output_dir: str) -> None:
    """Export all tables to CSV files.

    This command creates separate CSV files for each table in the database.

    Example:
        datamultiplier dump-all --db-url postgresql://user:pass@localhost/mydb \\
            --output-dir ./backups
    """
    click.echo(f"Exporting all tables from schema '{schema}'...")
    click.echo(f"  Output directory: {output_dir}")

    db = DatabaseConnection(db_url, schema=schema)
    db.connect()
    click.echo(f"✓ Connected")

    try:
        dumper = DataDumper(db)
        dumper.dump_all_tables_to_csv(output_dir)
        click.echo(f"✓ Export complete")

    finally:
        db.disconnect()


if __name__ == "__main__":
    main()
